# Generated by Django 4.1.7 on 2023-03-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_phone', models.CharField(max_length=100)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_pass', models.CharField(max_length=100)),
                ('u_pass1', models.CharField(max_length=100)),
            ],
        ),
    ]
