# Generated by Django 2.2 on 2023-02-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quan',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
